name: dartbug
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  gcp: ^0.1.0
  http: ^0.13.4
  shelf: ^1.0.0

dev_dependencies:
  github: ^9.0.0
  lints: ^2.0.0
  test: ^1.3.0
